apiVersion: v1
kind: Secret
metadata:
  name: awscomp
type: Opaque
stringData:
   accesskey: 'XKIAOF3XXCNCA4ZKVZ6A' #EXAMPLE
   secretkey: 'XTNmxPaEV9yrC732kAhCEhjUawVVMQ51xUPIFJiO' #EXAMPLE

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: zendesk-comprehiend

spec:
  template:
    metadata:
        annotations:
          autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: ko://github.com/triggermesh/transformations/zenformation/
    # or comment the above block out and uncomment the below block to ship from a pre-built container.
    # - image: gcr.io/neffdev/zenformation:latest
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom: 
            secretKeyRef:
              name: awscomp
              key: accesskey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom: 
            secretKeyRef:
              name: awscomp
              key: secretkey
        - name: LANGUAGE
          value: 'en' #Example 
        - name: AWS_REGION
          value: 'us-east-1' #Example 
        - name: K_SINK
          value: 'https://event-display.zendesk.dev.munu.io'  #Example <- This line, and the one above it, can be removed if you want zenformation to reply to the sender.
